# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1BfW3GU73xgR8ZG_S64ZvhWNhsuzpbJRC
"""

from flask import Flask, render_template, request, jsonify
import cv2
import numpy as np
import base64

app = Flask(__name__)

# This is where your backend logic lives
@app.route('/process', methods=['POST'])
def process_image():
    data = request.json
    image_data = data['image'].split(',')[1] # Get the base64 string
    bg_color = data['color']

    # 1. Decode the image into a format OpenCV understands
    nparr = np.frombuffer(base64.b64decode(image_data), np.uint8)
    img = cv2.imdecode(nparr, cv2.IMREAD_COLOR)

    # 2. CALL YOUR AI LOGIC HERE
    # Use the logic from your model_training.py to remove the background
    # processed_img = your_segmentation_function(img)

    # 3. For now, let's just return the image to confirm connection
    _, buffer = cv2.imencode('.png', img)
    processed_b64 = base64.b64encode(buffer).decode('utf-8')

    return jsonify({
        'success': True,
        'processed_image': f"data:image/png;base64,{processed_b64}"
    })

@app.route('/')
def home():
    return render_template('index.html')

if __name__ == '__main__':
    app.run(debug=True)

