# -*- coding: utf-8 -*-
"""Model_Training.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zQybhxkckTtCJwl9ePTLotqZCezJbxnq
"""

!unzip mask.zip

!unzip IMAGES.zip

import xml.etree.ElementTree as ET
import cv2
import numpy as np
import os

def create_masks_from_xml(xml_file_path, image_dir, output_mask_dir):
    """
    Parses CVAT annotations from an XML file and generates binary masks.
    """
    if not os.path.exists(output_mask_dir):
        os.makedirs(output_mask_dir)

    try:
        tree = ET.parse(xml_file_path)
        root = tree.getroot()

        for image_element in root.findall('image'):
            image_name = image_element.get('name')
            image_width = int(image_element.get('width'))
            image_height = int(image_element.get('height'))

            mask = np.zeros((image_height, image_width), dtype=np.uint8)
            polygon_element = image_element.find('polygon')

            if polygon_element is not None:
                points_string = polygon_element.get('points')
                coord_pairs = points_string.split(';')

                coordinates = []
                for pair in coord_pairs:
                    x, y = map(float, pair.split(','))
                    coordinates.append((int(x), int(y)))

                points_array = np.array(coordinates, dtype=np.int32)
                points_array = points_array.reshape((-1, 1, 2))
                cv2.fillPoly(mask, [points_array], 255)

            mask_save_path = os.path.join(output_mask_dir, image_name)
            cv2.imwrite(mask_save_path, mask)

    except FileNotFoundError:
        print(f"Error: The file '{xml_file_path}' was not found.")
    except ET.ParseError:
        print(f"Error: Failed to parse the XML file. Check its format.")

xml_file = 'annotations.xml'
images_folder = 'IMAGES'
masks_folder = 'MASKS'
create_masks_from_xml(xml_file, images_folder, masks_folder)

import torch
from torch.utils.data import Dataset, DataLoader
import os
import cv2
import numpy as np
import re

class SegmentationDataset(Dataset):
    def __init__(self, image_dir, mask_dir, transform=None):
        self.image_dir = image_dir
        self.mask_dir = mask_dir
        self.transform = transform

        def get_num(filename):
            match = re.search(r'\d+', filename)
            return int(match.group()) if match else -1

        image_filenames = sorted([f for f in os.listdir(image_dir) if f.lower().endswith(('.jpg', '.jpeg', '.png'))], key=get_num)
        mask_filenames = sorted([f for f in os.listdir(mask_dir) if f.lower().endswith(('.jpg', '.jpeg', '.png'))], key=get_num)

        self.images = image_filenames
        self.masks = mask_filenames

        if len(self.images) != len(self.masks):
            print("Warning: Number of images and masks do not match!")

    def __len__(self):
        return len(self.images)

    def __getitem__(self, idx):
        img_name = self.images[idx]
        mask_name = self.masks[idx]

        img_path = os.path.join(self.image_dir, img_name)
        mask_path = os.path.join(self.mask_dir, mask_name)

        image = cv2.imread(img_path)
        image = cv2.cvtColor(image, cv2.COLOR_BGR2RGB)

        mask = cv2.imread(mask_path, cv2.IMREAD_GRAYSCALE)
        mask = (mask > 0).astype(np.float32)

        # --- Data Augmentation ---
        if np.random.rand() < 0.5:  # 50% chance of flipping
            image = cv2.flip(image, 1)  # Horizontal flip
            mask = cv2.flip(mask, 1)    # Horizontal flip

        # Add other transformations like rotation, scaling, etc. here

        # --- Resize images and masks to a fixed size ---
        image = cv2.resize(image, (256, 256))
        mask = cv2.resize(mask, (256, 256), interpolation=cv2.INTER_NEAREST) # Use nearest neighbor for masks to preserve boundaries


        image = torch.from_numpy(np.transpose(image, (2, 0, 1)))
        mask = torch.from_numpy(mask)

        return image, mask

from torch import nn
import torch.nn.functional as F

class DoubleConv(nn.Module):
    def __init__(self, in_channels, out_channels):
        super(DoubleConv, self).__init__()
        self.conv = nn.Sequential(
            nn.Conv2d(in_channels, out_channels, 3, 1, 1, bias=False),
            nn.BatchNorm2d(out_channels),
            nn.ReLU(inplace=True),
            nn.Conv2d(out_channels, out_channels, 3, 1, 1, bias=False),
            nn.BatchNorm2d(out_channels),
            nn.ReLU(inplace=True),
        )

    def forward(self, x):
        return self.conv(x)

class UNET(nn.Module):
    def __init__(self, in_channels=3, out_channels=1):
        super(UNET, self).__init__()
        self.ups = nn.ModuleList()
        self.downs = nn.ModuleList()
        self.pool = nn.MaxPool2d(kernel_size=2, stride=2)

        features = [64, 128, 256, 512]

        for feature in features:
            self.downs.append(DoubleConv(in_channels, feature))
            in_channels = feature

        for feature in reversed(features):
            self.ups.append(nn.ConvTranspose2d(feature * 2, feature, kernel_size=2, stride=2))
            self.ups.append(DoubleConv(feature * 2, feature))

        self.bottleneck = DoubleConv(features[-1], features[-1] * 2)
        self.final_conv = nn.Conv2d(features[0], out_channels, kernel_size=1)

    def forward(self, x):
        skip_connections = []

        for down in self.downs:
            x = down(x)
            skip_connections.append(x)
            x = self.pool(x)

        x = self.bottleneck(x)
        skip_connections = skip_connections[::-1]

        for idx in range(0, len(self.ups), 2):
            x = self.ups[idx](x)
            skip_connection = skip_connections[idx // 2]

            if x.shape != skip_connection.shape:
                x = F.interpolate(x, size=skip_connection.shape[2:], mode='bilinear', align_corners=True)

            concat_skip = torch.cat((skip_connection, x), dim=1)
            x = self.ups[idx + 1](concat_skip)

        return self.final_conv(x)

model = UNET(in_channels=3, out_channels=1)

import torch.optim as optim
from tqdm import tqdm
from torch import nn

# Set device to GPU if available
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
model.to(device)

# Define optimizer and loss function
optimizer = optim.Adam(model.parameters(), lr=1e-4)
loss_fn = nn.BCEWithLogitsLoss()

def dice_score(pred, target):
    smooth = 1e-5
    pred_flat = pred.view(-1)
    target_flat = target.view(-1)
    intersection = (pred_flat * target_flat).sum()
    union = pred_flat.sum() + target_flat.sum()
    dice = (2. * intersection + smooth) / (union + smooth)
    return dice.item()

def evaluate_model(model, data_loader, device):
    model.eval()
    total_dice_score = 0.0
    with torch.no_grad():
        for images, masks in tqdm(data_loader, desc="Evaluating"):
            images = images.to(device)
            masks = masks.to(device)

            outputs = model(images.float())
            preds = torch.sigmoid(outputs)
            preds = (preds > 0.5).float()

            total_dice_score += dice_score(preds, masks)

    avg_dice_score = total_dice_score / len(data_loader)
    return avg_dice_score

# Training loop
epochs = 5
for epoch in range(epochs):
    model.train()
    total_loss = 0.0
    for images, masks in tqdm(train_loader, desc=f"Epoch {epoch+1}"):
        images = images.to(device).float()
        masks = masks.to(device).float()

        # Forward pass
        outputs = model(images)
        loss = loss_fn(outputs.squeeze(1), masks)

        # Backward pass and optimize
        optimizer.zero_grad()
        loss.backward()
        optimizer.step()

        total_loss += loss.item()

    avg_loss = total_loss / len(train_loader)
    print(f"Epoch {epoch+1}/{epochs}, Loss: {avg_loss:.4f}")

    # Evaluate after each epoch
    avg_dice = evaluate_model(model, train_loader, device)
    print(f"Average Dice Score on the dataset: {avg_dice:.4f}")

# Create dataset and data loaders
dataset = SegmentationDataset(image_dir='IMAGES', mask_dir='MASKS')
train_size = int(0.8 * len(dataset))
eval_size = len(dataset) - train_size
train_dataset, eval_dataset = torch.utils.data.random_split(dataset, [train_size, eval_size])

train_loader = DataLoader(train_dataset, batch_size=4, shuffle=True)
eval_loader = DataLoader(eval_dataset, batch_size=4, shuffle=False)

model_save_path = '/content/drive/My Drive/unet_segmentation_model.pth'
torch.save(model.state_dict(), model_save_path)
print(f"Model saved to {model_save_path}")

from google.colab import drive
drive.mount('/content/drive')

"""##**BACKEND CODE**"""

!pip install Flask flask-cors

"""# Task
Set up a backend for a Flask application, expose it using ngrok, and test it.

## Setup ngrok

### Subtask:
Install and configure ngrok to expose the local Flask server to the internet.

**Reasoning**:
Install the `pyngrok` library to interact with ngrok from Python.
"""

!pip install pyngrok

"""**Reasoning**:
Configure ngrok with the authentication token.


"""

from google.colab import userdata
import os

# Get the ngrok authtoken from Colab secrets
NGROK_AUTH_TOKEN = userdata.get('NGROK_AUTH_TOKEN')

# Set the ngrok authtoken
if NGROK_AUTH_TOKEN:
    !ngrok authtoken $NGROK_AUTH_TOKEN
else:
    print("Ngrok authtoken not found in secrets. Please add it.")

"""## Refactor flask app

### Subtask:
Modify the Flask application code to ensure the model is loaded correctly within the app context and the routes are properly defined to handle incoming requests.

**Reasoning**:
The Flask application code needs to be modified to ensure the model is loaded correctly within the app context and the routes are properly defined to handle incoming requests. The current code loads the model at the module level, which is not ideal for a Flask app. I will wrap the model loading in a function and call it when the app starts, and ensure the route is correctly defined.

## Run Flask App with ngrok

### Subtask:
Start the Flask application and use ngrok to create a public URL for accessing the API.

**Reasoning**:
Use `pyngrok` to start the Flask application and create a public URL. This allows external requests to reach the Flask server running in Colab.
"""



from pyngrok import ngrok
import threading
import time
import sys

# Terminate open tunnels if any
ngrok.kill()

# Start the Flask app in a separate thread
def run_flask():
    # Use a production server like Waitress instead of the Flask dev server in a real application
    # For this example, we'll keep the debug server for simplicity
    app.run(debug=True, host='0.0.0.0', port=5000, use_reloader=False) # Set use_reloader to False

flask_thread = threading.Thread(target=run_flask)
flask_thread.daemon = True # Allow the main thread to exit even if the Flask thread is running
flask_thread.start()

# Wait a bit for the server to start
time.sleep(5)

# Open a ngrok tunnel to the Flask app's port
try:
    public_url = ngrok.connect(5000).public_url
    print(f" * ngrok tunnel established at {public_url}")

    # Keep the main thread alive while the Flask server and ngrok are running
    try:
        while True:
            time.sleep(1)
    except KeyboardInterrupt:
        print(" * Shutting down ngrok tunnel and Flask server.")
        ngrok.kill()
        sys.exit(0)

except Exception as e:
    print(f"Error starting ngrok or Flask app: {e}")
    ngrok.kill()
    sys.exit(1)

!pip install flask-cors

from flask import Flask, request, jsonify
from flask_cors import CORS
import torch
import os

app = Flask(__name__)
CORS(app)

# Variable to hold the loaded model
model = None
model_save_path = '/content/drive/My Drive/unet_segmentation_model.pth' # Make sure this path is correct

def load_model():
    """Loads the trained model."""
    global model
    if model is None:
        # Assuming UNET class is defined in a previous cell
        model = UNET(in_channels=3, out_channels=1)
        if os.path.exists(model_save_path):
            # Load the state dictionary
            model.load_state_dict(torch.load(model_save_path, map_location=torch.device('cpu')))
            model.eval() # Set the model to evaluation mode
            print("Model loaded successfully.")
        else:
            print(f"Warning: Model file not found at {model_save_path}. The model will not be loaded.")

# Load the model when the app starts
with app.app_context():
    load_model()

@app.route('/')
def index():
    return "Flask app is running!"

# Add other routes here, for example, a route for processing images
# @app.route('/predict', methods=['POST'])
# def predict():
#     if 'image' not in request.files:
#         return jsonify({'error': 'No image provided'}), 400
#
#     file = request.files['image']
#     # Process the image using the loaded model
#     # ... (add image loading, preprocessing, model inference, postprocessing)
#
#     return jsonify({'message': 'Image processed (placeholder)'}) # Replace with actual results

if __name__ == '__main__':
    # This block is typically used for running the Flask dev server directly
    # In Colab with ngrok, the app is run via a separate thread, so this part
    # might not be directly executed in this Colab setup.
    # app.run(debug=True, host='0.0.0.0', port=5000)
    pass # Keep this empty as ngrok will handle running the app

